services:
  web:
    build:
      context: .
      dockerfile: ./scripts/docker/django/Dockerfile
    command: gunicorn grore.wsgi:application --bind ${DJANGO_HOST}:${DJANGO_PORT}
    volumes:
      - static_volume:${DJANGO_STATIC_ROOT}
      - media_volume:${DJANGO_MEDIA_ROOT}
    expose:
      - ${DJANGO_PORT}
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:${DOCKER_POSTGRES_ROOT}
    env_file:
      - ./.env
  nginx:
    build: ./scripts/docker/nginx
    volumes:
      - static_volume:${DJANGO_STATIC_ROOT}
      - media_volume:${DJANGO_MEDIA_ROOT}
    ports:
      - 1337:80
    depends_on:
      - web
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  media_volume: