services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    entrypoint: ["./entrypoint.sh"]
    command: python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    volumes:
      - .:/usr/src/grore/
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: