services:
  django:
    build: 
      context: .
      dockerfile: ./scripts/docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/usr/src/grore/
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    # expose:
    #   - ${DJANGO_PORT}
    env_file:
      - ./.env
    environment:
      DATABASE: "postgres"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DJANGO_MEDIA_ROOT: /home/grore/web/cache/media
      DJANGO_MEDIA_URL: media
      DJANGO_STATIC_ROOT: /home/grore/web/cache/staticfiles
      DJANGO_STATIC_URL: static
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: grore
      POSTGRES_USER: groreuser
      POSTGRES_PASSWORD: grorepassword
volumes:
  postgres_data: