services:
  web:
    build: .
    command: python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    volumes:
      - .:/usr/src/grore/
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: