services:
  django:
    build: 
      context: ${APP_DJANGO_ROOT}
      dockerfile: ${APP_DJANGO_ROOT}/Dockerfile
      args: 
        APP_DJANGO_ROOT: ${APP_DJANGO_ROOT}
        APP_DJANGO_USER_USER: ${APP_DJANGO_USER_USER}
        APP_DJANGO_USER_GROUP: ${APP_DJANGO_USER_GROUP}
        APP_DJANGO_USER_UID: ${APP_DJANGO_USER_UID}
        APP_DJANGO_USER_GID: ${APP_DJANGO_USER_GID}
    command: sh ${APP_DJANGO_ROOT}/entrypoint.sh
    user: ${APP_DJANGO_USER_UID}:${APP_DJANGO_USER_GID}
    volumes:
      - ./:${APP_DJANGO_ROOT}:rw
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      ENVIRONEMENT: "docker"
      DEBUG: True 
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  postgres_data: