volumes:
  grore_postgres_volume:
    name: grore_postgres_volume

services:
  postgres:
    image: postgres:14-alpine
    user: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/grore_postgres_volume/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}  
