# Generated by Django 5.0.1 on 2024-02-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
