# Generated by Django 5.2.6 on 2026-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_slug_alter_page_title_alter_page_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_fr',
            field=models.TextField(null=True),
        ),
    ]
