# Generated by Django 5.0.1 on 2024-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
