# Generated by Django 5.0.1 on 2024-02-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='note_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='note_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='note',
            field=models.TextField(),
        ),
    ]
