# Generated by Django 5.0.1 on 2024-02-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_note_en_image_note_fr_alter_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='note',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='note_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='note_fr',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
