# Generated by Django 5.0.1 on 2024-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
