# Generated by Django 5.2.6 on 2026-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='high_res',
            field=models.BooleanField(default=False),
        ),
    ]
