# Generated by Django 5.2.6 on 2026-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_high_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
    ]
