# Generated by Django 5.2.6 on 2026-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_image_thumbnail_image_zoom_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ai_gen',
            field=models.BooleanField(default=False),
        ),
    ]
