# Generated by Django 5.2.6 on 2026-08-13 20:34
from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_image_ai_gen'),
    ]

    operations = [
        VectorExtension(),
    ]