# Generated by Django 5.2.6 on 2026-08-15 14:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='note_en_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='note_fr_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
